name: DiscordSocialSpy
description: Sends a message to Discord when a player successfully executes a command.

author: SavageAvocado
website: savagedev.net

api-version: 1.13
main: net.savagedev.discordsocialspy.DiscordSocialSpyPlugin
version: ${version}

commands:
  discordsocialspy:
    description: Reload the plugin.
    permission: dss.reload
    usage: /<command> reload
    aliases: [ dss ]

permissions:
  dss.reload:
    default: op
